#!/bin/bash -e
exec > >(tee -a -i /var/log/runonce.log) 2>&1

# Create or modify group bluetooth.
if ! getent group 'bluetooth'; then
    groupadd -r -g 112 bluetooth || true

else
    groupmod -g 112 bluetooth || true

fi

# Create or modify group lpadmin.
if ! getent group 'lpadmin'; then
    groupadd -r -g 113 lpadmin || true

else
    groupmod -g 113 lpadmin || true

fi

# Create or modify group scanner.
if ! getent group 'scanner'; then
    groupadd -r -g 122 scanner || true

else
    groupmod -g 122 scanner || true

fi

# Create or modify group threat.
if ! getent group 'threat'; then
    groupadd -g 1000 threat || true

else
    groupmod -g 1000 threat || true

fi

# Default groups.
threat_groups="adm,audio,cdrom,dialout,dip,games,input,netdev,plugdev,render,\
staff,sudo,systemd-journal,users,video,scanner,threat"

# Check that the application groups exist.
app_groups="wireshark kismet i2c"
for g in $app_groups; do
    if getent group "$g" >/dev/null; then
        threat_groups+=",$g"

    fi
done

# Add the threat user and give them all the access they need.
if ! getent passwd 'threat'; then
    if [ $(arch) == 'armv6l' ]; then
        adduser --gecos "" --uid 1000 --gid 1000 --shell /usr/bin/bash --disabled-password threat

    else
        adduser --gecos "" --uid 1000 --gid 1000 --shell /usr/bin/zsh --disabled-password threat

    fi

    usermod -a -G "$threat_groups" threat
    echo 'threat:threat' | chpasswd
fi

# Parts of XFCE aren't being installed correctly despite existing in /etc/skel
# So we copy them in here, now that the threat user is created
# TODO: make this configurable when we allow users to specify their own user.
cp -rT /etc/skel /home/threat

# Reload and trigger udev rule
udevadm control --reload-rules
udevadm trigger
