name: Device Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Prerequisites
        run: |
          python -m pip install -r docs/requirements.txt
          python -m pip install yamllint
          
      - name: Linting
        run: yamllint devices.yml

  generate_documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Prerequisites
        run: |
          python -m pip install -r docs/requirements.txt

      - name: Setup for HTML
        run: |
          mkdir -p /tmp/pandoc
          wget -O /tmp/pandoc/pandoc.deb https://github.com/jgm/pandoc/releases/download/2.14.1/pandoc-2.14.1-1-amd64.deb
          sudo dpkg -i /tmp/pandoc/pandoc.deb || true
          sudo apt-get install -f
          rm -r /tmp/pandoc

      - name: Generate Documentation
        run: |
          ./bin/generate_devices_stats.py
          ./bin/generate_devices_table.py
          ./bin/generate_images_overview.py
          ./bin/generate_images_stats.py
          ./bin/generate_images_table.py
          ./bin/generate_kernel_stats.py
          mkdir -pv ./public/
          cp -v ./docs/404.html   ./public/
          cp -v ./docs/public.css ./public/
          pandoc --standalone ./docs/www.md    --css=public.css --include-in-header=./docs/header.html --output=./public/index.html
          pandoc --standalone ./device-stats.md   --css=public.css --include-in-header=./docs/header.html --output=./public/device-stats.html
          pandoc --standalone ./devices.md        --css=public.css --include-in-header=./docs/header.html --output=./public/devices.html
          pandoc --standalone ./image-overview.md --css=public.css --include-in-header=./docs/header.html --output=./public/image-overview.html
          pandoc --standalone ./image-stats.md    --css=public.css --include-in-header=./docs/header.html --output=./public/image-stats.html
          pandoc --standalone ./images.md         --css=public.css --include-in-header=./docs/header.html --output=./public/images.html
          pandoc --standalone ./kernel-stats.md   --css=public.css --include-in-header=./docs/header.html --output=./public/kernel-stats.html
          find public/ -type f -name '*.html' | sort | while read -r x; do sed 's_<table>_<table id="pretty">_' "${x}" > /tmp/out; mv /tmp/out "${x}"; done
